name: Create Release and Upload Website
on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Zip the built files
        run: zip -r website.zip dist

      - name: Create Release and Upload Website
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release-$(date +'%Y%m%d%H%M%S')"
          title: Release $(date +'%Y%m%d%H%M%S')
          files: ./website.zip